# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Where does the gold become blue?
email: daniel@thzinc.com
description: > # this means to ignore newlines until "baseurl:"
  Where does the gold become blue? Based on a tweet by @smartereveryday
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: thzinc
github_username:  thzinc

# Build settings
markdown: kramdown
